version: '3.7'
services:
  web:
    stdin_open: true # <-- Added this line
    container_name: docker-react-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3939:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
